# Dependencies
#markdown:         redcarpet # // not supported on Jekyll 4+
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true # // not supported on Jekyll 3+

# Setup
title:            REINHARDT
#tagline:          'A Jekyll theme'
tagline:          'endeavor'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description: > # this means to ignore newlines until "baseurl:"
  My personal cove to recover, contemplate, and share. Building the space I need to step beyond my plateaus.
#url:              http://hyde.getpoole.com
url: "http://reinhardt021.github.io/" # the base hostname & protocol for your site
#baseurl:          /
baseurl: "" # the subpath of your site, e.g. /blog


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

#github:
  #repo:           https://github.com/poole/hyde
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
